### PR TITLE
publish to Sonatype instead

### PR DESCRIPTION
**Pull request by joshk0**
following LiveRamp/daemon_lib#26

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/hank/342)

### CODE REVIEW

**Comment by joshk0** [comment]
@tuliren -- any idea why the build is failing here? don't think it was me

**Comment by tuliren** [comment]
No idea. Maybe there is a flaky unit test?

**Comment by tuliren** [comment]
According to the build history, this does look like a flaky unit test.

Screenshot 2019-04-01 18 13 05

One approach is maybe to increase the amount of sleep time in the failed unit test. But I don't know anything about hank, I am not sure if that would be a reasonable change.

**Comment by joshk0** [comment]
oh ok, i got confused who to ask, maybe @bpodgursky could chime in here

**Comment by bpodgursky** [comment]
let's just comment it out for now.  we won't be using this after PS is on bigtable.

**Pull request merged**
